### ISSUE TITLE
Time required for Activities to appear once published in registry?

### ISSUE THREAD

**Issue by anjesh** [DFID/devtracker-from-api#193]
How long does it take for the projects to appear in the devtracker once XML is published in the registry?

**Comment by johnadamsDFID** [comment]
Hi Anjesh
We schedule once you month but occasionally more frequently manually. We are looking into a more frequent schedule.

Why do you ask?

John

**Comment by anjesh** [comment]
Hi John,

Thank you for the quick reply.

There are number of AidStream organisations who have just published their XML files to registry and their fund manager are looking into the devtracker for compliance. Number of these organisations are worried that it's only appearing in registry but not in devtracker. I was thinking it's nightly run. Perhaps they can now point to this thread if their information doesn't appear in devtracker right after their xml is published. 

Please see the text from one of the emails to the publishing organisation.
---
As part of our ongoing compliance checks, we have noticed that your GPAF/UK Aid Direct grant is not showing up on Dev Tracker (www.devtracker.dfid.gov.uk<http://www.devtracker.dfid.gov.uk>).

In line with your contract grant arrangement with DFID, you are required to ensure that you are working towards being IATI compliant. This means that you need to ensure that your IATI data is up-to-date and published correctly on a quarterly basis. If your data is correctly published, then it should be visible on Dev Tracker and listed under UK Aid Direct as a partner.
---

**Comment by johnadamsDFID** [comment]
I will speak to the team about running a refresh over the next few days.

**Comment by anjesh** [comment]
Many thanks John.
